pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                echo "Buidling the code using 'Maven'..."
            }
        }
        stage('Unit and Integration Tests'){
            steps{
                echo "Performing unit tests using 'JUnit'..."
                echo "Performing integration tests using 'TestNG'..."
            }
            post{
                always {
                    emailext(
                            body: """
                                After Testing Build Status: ${currentBuild.currentResult}
            
                                Check the console output at: ${env.BUILD_URL}
                            """,
                            to: 'sm.sanuri.d@gmail.com',
                            subject: "Pipeline Build Status: ${currentBuild.currentResult} - Build #${env.BUILD_NUMBER}",
                            mimeType: 'text/plain',
                            attachLog: true
                        )
                }
            }
        }
        stage('Code Analysis'){
            steps{
                echo "Analysing the code using 'SonarQube'..."
            }
        }
        stage('Security Scan'){
            steps{
                echo "Performing a security scan on the code using 'Snyk'..."
            }
            post{
                always {
                    emailext(
                            body: """
                                After Security Scanning Build Status: ${currentBuild.currentResult}
            
                                Check the console output at: ${env.BUILD_URL}
                            """,
                            to: 'sm.sanuri.d@gmail.com',
                            subject: "Pipeline Build Status: ${currentBuild.currentResult} - Build #${env.BUILD_NUMBER}",
                            mimeType: 'text/plain',
                            attachLog: true
                        )
                }
            }
        }
        stage('Deploy to Staging'){
            steps{
                echo "Deploying the application to 'AWS EC2' staging server..."
            }
        }
        stage('Integration Tests on Staging'){
            steps{
                echo "Performing integration tests using 'Selenium'..."
            }
        }
        stage('Deploy to Production'){
            steps{
                echo "Deploying the application to 'AWS EC2' production server..."
            }
        }
    }
}
